name: cd
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          token: ${{ secrets.PAT }}
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/mist.key
          chmod 600 ~/.ssh/mist.key
          cat >>~/.ssh/config <<END
          Host api.mist-cloud.io
            HostName api.mist-cloud.io
            User mist
            IdentityFile ~/.ssh/mist.key
            StrictHostKeyChecking no
          END
          echo "api.mist-cloud.io ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOW2dgo+0nuahOzHD7XVnSdrCwhkK9wMnAZyr6XOKotO" >> ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: Deploy
        run: |
          git checkout ${GITHUB_REF#refs/heads/}
          git remote add mist ${{ secrets.MIST_SERVICE_REPO }}
          git push mist main:main --force